[env]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.6.0
    ESP32Async/AsyncTCP @ ^3.3.2
    adafruit/RTClib @ ^2.1.3
    bblanchon/ArduinoJson @ ^6.21.5

[env:irrigation]
build_flags = -DMODULE_IRRIGATION
build_src_filter = +<main.cpp> +<web/> +<modules/irrigation/>

[env:lighting]
build_flags = -DMODULE_LIGHTING
build_src_filter = +<main.cpp> +<web/> +<modules/lighting/>

[env:unified_all_in_one]
build_flags =
    -DMODULE_IRRIGATION
    -DMODULE_LIGHTING
build_src_filter = +<main.cpp> +<web/> +<modules/irrigation/> +<modules/lighting/>

[platformio]
default_envs = unified_all_in_one
